name: Connection test

on:
  workflow_dispatch

jobs:
#   build:
#     runs-on: windows-latest

#     steps:
#       - uses: actions/checkout@v2

#       - name: Setup MSBuild path
#         uses: microsoft/setup-msbuild@v1.0.2

#       - name: Setup NuGet
#         uses: NuGet/setup-nuget@v1.0.5

#       - name: Restore NuGet packages
#         run: nuget restore

#       - name: Publish to folder
#         run: msbuild /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="\published\"

#       - name: Upload artifact for deployment job
#         uses: actions/upload-artifact@v2
#         with:
#           name: ASP-app
#           path: '/published/**'

  deploy:
    runs-on: windows-latest
#     needs: build
    
    steps:
#       - name: Download artifact from build job
#         uses: actions/download-artifact@v2
#         with:
#           name: ASP-app
          
    

      - uses: Azure/login@v1
        with:
         creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
